- name: GitのPPAを追加する
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa

- name: aptリポジトリーを更新する
  ansible.builtin.apt:
    update_cache: yes

- name: aptパッケージを更新する
  ansible.builtin.apt:
    upgrade: yes

- name: aptパッケージをインストールする
  ansible.builtin.apt:
    pkg: "{{ item }}"
  loop: "{{ apt_packages }}"

- name: anyenvのインストール状態を確認する
  ansible.builtin.stat:
    path: ~/.anyenv/bin/anyenv
  register: anyenv_installed

- name: anyenvをインストールする
  ansible.builtin.git:
    repo: https://github.com/anyenv/anyenv.git
    dest: ~/.anyenv
  when: anyenv_installed.stat.exists == false

- name: anyenvの初期化状態を確認する
  ansible.builtin.stat:
    path: ~/.config/anyenv/anyenv-install
  register: anyenv_initialized

- name: anyenvを初期化する
  ansible.builtin.shell: ~/.anyenv/bin/anyenv install --force-init
  when: anyenv_initialized.stat.exists == false

- name: anyenvのプラグインディレクトリーを作成する
  ansible.builtin.file:
    path: ~/.anyenv/plugins
    state: directory

- name: envsのインストール状態を確認する
  ansible.builtin.stat:
    path: "~/.anyenv/envs/{{ item }}"
  register: anyenv_envs_installed
  loop: "{{ anyenv_envs }}"

- name: envsをインストールする
  ansible.builtin.shell: "~/.anyenv/bin/anyenv install {{ item }}"
  when: anyenv_envs_installed.results[loop_index].stat.exists == false
  loop: "{{ anyenv_envs }}"
  loop_control:
    index_var: loop_index

- name: anyenv-updateのインストール状態を確認する
  ansible.builtin.stat:
    path: ~/.anyenv/plugins/enyenv-update
  register: anyenv_update_installed

- name: anyenv-updateをインストールする
  ansible.builtin.git:
    repo: https://github.com/znz/anyenv-update.git
    dest: ~/.anyenv/plugins/enyenv-update
  when: anyenv_update_installed.stat.exists == false

- name: bashの一時プロファイルをコピーする
  ansible.builtin.copy:
    src: roles/wsl_apps/files/.bash_profile
    dest: ~/.bash_profile

- name: nodenvのバージョンを確認する
  ansible.builtin.stat:
    path: "~/.anyenv/envs/nodenv/versions/{{ item }}"
  register: nodenv_versions_installed
  loop: "{{ nodenv_versions }}"

- name: nodenvのバージョンをインストールする
  ansible.builtin.shell: "bash -lc '~/.anyenv/envs/nodenv/bin/nodenv install {{ item }}'"
  when: nodenv_versions_installed.results[loop_index].stat.exists == false
  loop: "{{ nodenv_versions }}"
  loop_control:
    index_var: loop_index

- name: bashの一時プロファイルを削除する
  ansible.builtin.file:
    path: ~/.bash_profile
    state: absent
