- name: レジストリを適用する
  community.windows.win_regmerge:
    path: "C:\\Windows\\Temp\\provision-windows\\roles\\win_settings\\files\\{{ item }}"
  loop: "{{ reg_files }}"

- name: パスワードを無期限にする
  ansible.windows.win_user:
    name: aikawame
    password_never_expires: yes

- name: Rictyフォントをコピーする
  ansible.windows.win_copy:
    src: /root/src/appdata-windows/Fonts/Ricty-Bold.ttf
    dest: C:\Windows\Fonts\Ricty-Bold.ttf

- name: Rictyフォントを有効化する
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts
    name: Ricty Bold (TrueType)
    data: Ricty-Bold.ttf

- name: Keyhacの設定を反映する
  ansible.windows.win_command: >
    cmd /k mklink /D
    C:\Users\aikawame\AppData\Roaming\Keyhac
    \\wsl.localhost\Ubuntu\root\src\appdata-windows\Keyhac

- name: Terminalの設定を反映する
  ansible.windows.win_command: >
    cmd /k mklink
    C:\Users\aikawame\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
    \\wsl.localhost\Ubuntu\root\src\appdata-windows\Terminal\settings.json

- name: Keyhacをスタートアップに登録する
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\bin\keyhac.exe
    dest: C:\Users\aikawame\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Keyhac.lnk

- name: スリープスクリプトをコピーする
  ansible.windows.win_copy:
    src: /root/src/appdata-windows/Powerman
    dest: C:\Users\aikawame\AppData\Roaming\Powerman

- name: スリープスクリプトのショートカットを追加する
  community.windows.win_shortcut:
    src: powershell C:\Users\aikawame\AppData\Roaming\Powerman\Sleep.ps1
    dest: C:\Users\aikawame\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Sleep.lnk
    icon: '%SystemRoot%\System32\SHELL32.dll,-26'
    windowstyle: minimized
