- name: Update apt repositories
  apt:
    update_cache: yes

- name: Update apt packages
  apt:
    upgrade: yes

- name: Install apt packages
  apt:
    pkg:
      - awscli
      - emacs25
      - peco
      - zsh

- name: Install anyenv
  git:
    repo: https://github.com/riywo/anyenv.git
    dest: ~/.anyenv
