appx_packages_unused:
  - Microsoft.549981C3F5F10
  - Microsoft.BingNews
  - Microsoft.BingWeather
# - Microsoft.DesktopAppInstaller # Win11で消そうとするとエラーになる
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.Paint
  - Microsoft.People
# - Microsoft.PowerAutomateDesktop
# - Microsoft.ScreenSketch
  - Microsoft.Todos
# - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
# - Microsoft.WindowsCalculator
  - Microsoft.WindowsCamera
  - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
# - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxGamingOverlay
  - Microsoft.XboxSpeechToTextOverlay
# - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams

chocolatey_packages:
  - 7zip.install
  - docker-desktop
  - firefox
  - GoogleChrome
  - intellijidea-ultimate
  - keyhac
  - Kindle
  - line
  - microsoft-windows-terminal
  - postman
  - powertoys
  - registrychangesview
  - rufus
  - slack
  - tableplus
