- name: 不要なAppxパッケージをアンインストールする
  ansible.windows.win_package:
    product_id: "{{ item }}"
    state: absent
  loop: "{{ appx_packages_unused }}"

- name: 必要なオプション機能をインストールする
  ansible.windows.win_optional_feature:
    name: "{{ item }}"
    state: present
  loop: "{{ optional_features }}"

- name: 不要なオプション機能をアンインストールする
  ansible.windows.win_optional_feature:
    name: "{{ item }}"
    state: absent
  loop: "{{ optional_features_unused }}"

- name: Chocolateyのパッケージをインストールする
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ chocolatey_packages }}"

 サイレントインストールの方法が不明
- name: Magic Utilitiesのインストール状態を確認する
  ansible.windows.win_stat:
    path: C:\Program Files (x86)\MagicUtilities
  register: magicutilities_installed

- name: Magic Utilitiesをダウンロードする
  ansible.windows.win_get_url:
    url: https://dwn-bcdn.magicutilities.net/downloads/MagicUtilities-Setup-3.1.1.4-Win10.exe
    dest: C:\Windows\Temp\provision-windows\MagicUtilities.exe
  when: magicutilities_installed.stat.exists == false

- name: Magic Utilitiesをインストールする
  ansible.windows.win_command: >
    C:\Windows\Temp\provision-windows\MagicUtilities.exe /SILENT
  when: magicutilities_installed.stat.exists == false

- name: ATOKのインストール状態を確認する
  ansible.windows.win_stat:
    path: C:\Program Files (x86)\JustSystems\ATOK
  register: atok_installed

- name: ATOKをダウンロードする
  ansible.windows.win_get_url:
    url: https://gate.justsystems.com/download/atok/ut/win/at32try1.exe
    dest: C:\Windows\Temp\provision-windows\attry.exe
  when: atok_installed.stat.exists == false

- name: ATOKを展開する
  ansible.windows.win_command: >
    '"C:\Program Files\7-zip\7z"
    x C:\Windows\Temp\provision-windows\attry.exe
    -oC:\Windows\Temp\provision-windows'
  when: atok_installed.stat.exists == false

- name: ATOKをインストールする
  ansible.windows.win_command: >
    C:\Windows\Temp\provision-windows\at32try1\ATOK\SETUP.EXE /s
  ignore_errors: yes
  when: atok_installed.stat.exists == false
